<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-D8C95I2" ignored="0" name="Retry failed tests" tests="7" failures="1" timestamp="06 Jul 2020 10:03:38 GMT" time="0.251" errors="0">
  <testcase name="test1" time="0.038" classname="testNG.RetryFailedTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.008" classname="testNG.RetryFailedTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.004" classname="testNG.RetryFailedTest"/>
  <testcase name="tryAgain" time="0.009" classname="testNG.RetryAgain">
    <skipped/>
  </testcase> <!-- tryAgain -->
  <testcase name="tryAgain" time="0.012" classname="testNG.RetryAgain">
    <skipped/>
  </testcase> <!-- tryAgain -->
  <testcase name="tryAgain" time="0.006" classname="testNG.RetryAgain">
    <skipped/>
  </testcase> <!-- tryAgain -->
  <testcase name="tryAgain" time="0.008" classname="testNG.RetryAgain">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNG.RetryAgain.tryAgain(RetryAgain.java:10)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tryAgain -->
</testsuite> <!-- Retry failed tests -->
