<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-D8C95I2" name="Retry failed tests" tests="4" failures="4" timestamp="29 Sep 2018 19:08:01 GMT" time="0.226" errors="0">
  <testcase name="test1" time="0.058" classname="testNG.RetryFailedTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at testNG.RetryFailedTest.test1(RetryFailedTest.java:10)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.005" classname="testNG.RetryFailedTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at testNG.RetryFailedTest.test1(RetryFailedTest.java:10)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.007" classname="testNG.RetryFailedTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at testNG.RetryFailedTest.test1(RetryFailedTest.java:10)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.005" classname="testNG.RetryFailedTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at testNG.RetryFailedTest.test1(RetryFailedTest.java:10)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- Retry failed tests -->
